version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh -c "flask run --host 0.0.0.0"
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - .env
      - .flaskenv
    depends_on:
      - db


volumes:
  postgres_data: