"""empty message

Revision ID: 309816fc4911
Revises: c7a2f23df61d
Create Date: 2023-07-06 18:03:22.323264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309816fc4911'
down_revision = 'c7a2f23df61d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
